// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.6.1.0
//      SpecFlow Generator Version:1.6.0.0
//      Runtime Version:4.0.30319.225
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace CMContrib.Spec.Rescue
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.6.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Calling a rescue action when results complete with an error")]
    public partial class CallingARescueActionWhenResultsCompleteWithAnErrorFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "RescueAction.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Calling a rescue action when results complete with an error", "As a programmer\r\nIn order to handle errors in completed results efficiently\r\nI wa" +
                    "nt to invoke an action as a rescue", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The rescue action is not invoked when the result completes")]
        public virtual void TheRescueActionIsNotInvokedWhenTheResultCompletes()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The rescue action is not invoked when the result completes", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given("an arbitrary result which completes");
#line 8
  testRunner.And("I want to rescue all errors with an action");
#line 9
 testRunner.When("the result is executed");
#line 10
 testRunner.Then("the rescue action is not invoked");
#line 11
  testRunner.And("the result does not get cancelled");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The rescue action is not invoked when the result is cancelled")]
        public virtual void TheRescueActionIsNotInvokedWhenTheResultIsCancelled()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The rescue action is not invoked when the result is cancelled", ((string[])(null)));
#line 13
this.ScenarioSetup(scenarioInfo);
#line 14
 testRunner.Given("an arbitrary result which gets cancelled");
#line 15
  testRunner.And("I want to rescue all errors with an action");
#line 16
 testRunner.When("the result is executed");
#line 17
 testRunner.Then("the rescue action is not invoked");
#line 18
  testRunner.And("the result gets cancelled");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The rescue action for all errors is invoked when the results completes with an er" +
            "ror")]
        public virtual void TheRescueActionForAllErrorsIsInvokedWhenTheResultsCompletesWithAnError()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The rescue action for all errors is invoked when the results completes with an er" +
                    "ror", ((string[])(null)));
#line 20
this.ScenarioSetup(scenarioInfo);
#line 21
 testRunner.Given("an arbitrary result which completes with an arbitrary error");
#line 22
  testRunner.And("I want to rescue all errors with an action");
#line 23
 testRunner.When("the result is executed");
#line 24
 testRunner.Then("the rescue action is invoked on the arbitrary exception");
#line 25
  testRunner.And("the result gets cancelled");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The rescue action for a specific error is invoked when the result completes with " +
            "the specific error")]
        public virtual void TheRescueActionForASpecificErrorIsInvokedWhenTheResultCompletesWithTheSpecificError()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The rescue action for a specific error is invoked when the result completes with " +
                    "the specific error", ((string[])(null)));
#line 27
this.ScenarioSetup(scenarioInfo);
#line 28
 testRunner.Given("an arbitrary result which completes with an ArgumentException");
#line 29
  testRunner.And("I want to rescue ArgumentException errors with an action");
#line 30
 testRunner.When("the result is executed");
#line 31
 testRunner.Then("the rescue action is invoked on the ArgumentException");
#line 32
  testRunner.And("the result gets cancelled");
#line 33
  testRunner.And("the result completes without an error");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The rescue action for a specific error is not invoked when the result completes w" +
            "ith another error")]
        public virtual void TheRescueActionForASpecificErrorIsNotInvokedWhenTheResultCompletesWithAnotherError()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The rescue action for a specific error is not invoked when the result completes w" +
                    "ith another error", ((string[])(null)));
#line 35
this.ScenarioSetup(scenarioInfo);
#line 36
 testRunner.Given("an arbitrary result which completes with an arbitrary error");
#line 37
  testRunner.And("I want to rescue ArgumentException errors with an action");
#line 38
 testRunner.When("the result is executed");
#line 39
 testRunner.Then("the rescue action is not invoked");
#line 40
  testRunner.And("the result does not get cancelled");
#line 41
  testRunner.And("the result completes with the arbitrary error");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
